version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=mydb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
    volumes:
      - static_volume:/app/testtask/static

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx_docker.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/testtask/static
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume: 